"""add_sessions_softdelete

Revision ID: 077c4236872b
Revises: 7d6800c05be9
Create Date: 2026-07-05 08:46:34.377605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077c4236872b'
down_revision: Union[str, Sequence[str], None] = '7d6800c05be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('parent_id', sa.Integer(), nullable=True, comment='父级会话ID'))
    op.add_column('sessions', sa.Column('status', sa.String(length=32), nullable=True, comment='状态: active/archived'))
    op.add_column('sessions', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标志'))
    op.create_foreign_key(None, 'sessions', 'sessions', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'is_deleted')
    op.drop_column('sessions', 'status')
    op.drop_column('sessions', 'parent_id')
    # ### end Alembic commands ###
