"""add_user_deleteandactive

Revision ID: 24781aa87fd2
Revises: a59af4d5c47b
Create Date: 2026-07-05 06:57:38.232421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24781aa87fd2'
down_revision: Union[str, Sequence[str], None] = 'a59af4d5c47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, comment='账号状态(True:正常/False:封禁)'))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除标志'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
