"""add_user_role

Revision ID: 340f8ad93b36
Revises: bdb9cdeeea46
Create Date: 2026-07-04 08:58:12.802559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340f8ad93b36'
down_revision: Union[str, Sequence[str], None] = 'bdb9cdeeea46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=32), nullable=True, comment='用户角色: student/admin'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
