"""modify_favorite_wrong_question_id

Revision ID: 667fd4feaac7
Revises: a59af4d5c47b
Create Date: 2026-07-05 07:53:48.716513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '667fd4feaac7'
down_revision: Union[str, Sequence[str], None] = 'a59af4d5c47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('content_id', sa.Integer(), nullable=False, comment='关联的源数据ID，配合content_type对应不同表'))
    op.alter_column('favorites', 'content_type',
               existing_type=mysql.VARCHAR(length=64),
               comment='收藏类型: 摘要/题目',
               existing_comment='收藏类型: 摘要/知识点/题目',
               existing_nullable=False)
    op.drop_column('favorites', 'content_data')
    op.add_column('wrong_questions', sa.Column('question_id', sa.Integer(), nullable=True, comment='关联的原题ID，方便追溯跳转'))
    op.create_foreign_key(None, 'wrong_questions', 'bank_questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wrong_questions', type_='foreignkey')
    op.drop_column('wrong_questions', 'question_id')
    op.add_column('favorites', sa.Column('content_data', mysql.TEXT(), nullable=False, comment='收藏的具体内容(存JSON)'))
    op.alter_column('favorites', 'content_type',
               existing_type=mysql.VARCHAR(length=64),
               comment='收藏类型: 摘要/知识点/题目',
               existing_comment='收藏类型: 摘要/题目',
               existing_nullable=False)
    op.drop_column('favorites', 'content_id')
    # ### end Alembic commands ###
