"""add_question_difficulty

Revision ID: 7ef9f8bee362
Revises: bdb9cdeeea46
Create Date: 2026-07-04 06:49:01.890624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef9f8bee362'
down_revision: Union[str, Sequence[str], None] = 'bdb9cdeeea46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_questions', sa.Column('my_analysis', sa.Text(), nullable=True, comment='我生成的解析'))
    op.add_column('wrong_questions', sa.Column('my_analysis', sa.Text(), nullable=True, comment='我生成的解析'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wrong_questions', 'my_analysis')
    op.drop_column('bank_questions', 'my_analysis')
    # ### end Alembic commands ###
