"""modify_attachment

Revision ID: a6da4d7f3a1a
Revises: c5bc5b53cb68
Create Date: 2026-07-07 08:45:15.178574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6da4d7f3a1a'
down_revision: Union[str, Sequence[str], None] = 'c5bc5b53cb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'extracted_text',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_comment='OCR或PDF解析出的纯文本',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'extracted_text',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_comment='OCR或PDF解析出的纯文本',
               existing_nullable=True)
    # ### end Alembic commands ###
