"""change_wrong_questions

Revision ID: b44d4ca973af
Revises: c5bc5b53cb68
Create Date: 2026-07-08 02:36:57.787192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b44d4ca973af'
down_revision: Union[str, Sequence[str], None] = 'c5bc5b53cb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wrong_questions', 'user_answer',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               comment='用户错误答案(JSON格式)',
               existing_comment='用户错误答案',
               existing_nullable=True)
    op.alter_column('wrong_questions', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               comment='正确答案(JSON格式)',
               existing_comment='正确答案',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wrong_questions', 'correct_answer',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               comment='正确答案',
               existing_comment='正确答案(JSON格式)',
               existing_nullable=True)
    op.alter_column('wrong_questions', 'user_answer',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               comment='用户错误答案',
               existing_comment='用户错误答案(JSON格式)',
               existing_nullable=True)
    # ### end Alembic commands ###
