"""Database_init

Revision ID: bdb9cdeeea46
Revises: 
Create Date: 2026-07-04 04:09:50.317988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb9cdeeea46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('wechat_openid', sa.String(length=128), nullable=False, comment='微信用户唯一标识'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='用户昵称'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像链接'),
    sa.Column('signature', sa.String(length=255), nullable=True, comment='个性签名'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wechat_openid')
    )
    op.create_table('question_banks',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('bank_name', sa.String(length=128), nullable=False, comment='题库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='题库描述或学习计划'),
    sa.Column('total_questions', sa.Integer(), nullable=True, comment='总题数(方便快速查询)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户ID'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='会话标题(AI自动生成)'),
    sa.Column('task_type', sa.String(length=64), nullable=True, comment='任务类型: 摘要/精讲/测验'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wrong_questions',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户ID'),
    sa.Column('question_content', sa.Text(), nullable=False, comment='题目完整文本'),
    sa.Column('source_image_url', sa.String(length=255), nullable=True, comment='原始拍照图片链接'),
    sa.Column('user_answer', sa.String(length=255), nullable=True, comment='用户错误答案'),
    sa.Column('correct_answer', sa.String(length=255), nullable=True, comment='正确答案'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI深度解析'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_questions',
    sa.Column('bank_id', sa.Integer(), nullable=False, comment='所属题库ID'),
    sa.Column('chapter_name', sa.String(length=128), nullable=True, comment='所属章节(用于支持"章节练习")'),
    sa.Column('question_type', sa.String(length=32), nullable=False, comment='题型: single_choice/multi_choice/essay 等(支持"题型练习")'),
    sa.Column('difficulty_level', sa.String(length=32), nullable=True, comment='难度: easy/medium/hard (支持"难度练习")'),
    sa.Column('content', sa.Text(), nullable=False, comment='题干内容'),
    sa.Column('options_json', sa.JSON(), nullable=True, comment='选项列表(JSON格式,如 ["A. 选项1", "B. 选项2"])'),
    sa.Column('correct_answer', sa.String(length=255), nullable=False, comment='正确答案'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI生成的解析'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户ID'),
    sa.Column('content_type', sa.String(length=64), nullable=False, comment='收藏类型: 摘要/知识点/题目'),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True, comment='列表展示用的封面/缩略图'),
    sa.Column('content_data', sa.Text(), nullable=False, comment='收藏的具体内容(存JSON)'),
    sa.Column('source_session', sa.Integer(), nullable=True, comment='来源会话ID, 方便追溯'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['source_session'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联会话ID'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='角色: user/assistant/system/tool'),
    sa.Column('content_type', sa.String(length=32), nullable=True, comment='内容类型: text/mixed'),
    sa.Column('content', sa.Text(), nullable=True, comment='具体内容(mixed时建议存JSON)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('bank_id', sa.Integer(), nullable=False, comment='所属题库ID'),
    sa.Column('practice_mode', sa.String(length=32), nullable=False, comment='练习模式: sequential/random/mock 等'),
    sa.Column('question_sequence', sa.JSON(), nullable=False, comment='生成的题目ID序列(维持顺序)，如 [15, 2, 8, 33]'),
    sa.Column('last_viewed_index', sa.Integer(), nullable=True, comment='最后停留的题目数组索引，用于中断后恢复'),
    sa.Column('status', sa.String(length=16), nullable=True, comment='状态: ongoing进行中, completed已交卷'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上传者ID'),
    sa.Column('message_id', sa.Integer(), nullable=True, comment='绑定的消息ID'),
    sa.Column('file_type', sa.String(length=64), nullable=True, comment='文件类型,如 image/jpeg'),
    sa.Column('file_url', sa.String(length=255), nullable=False, comment='云端对象存储链接'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='OCR或PDF解析出的纯文本'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_records',
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联的练习会话ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='题目ID'),
    sa.Column('is_completed', sa.Boolean(), nullable=True, comment='是否已作答(用来渲染答题卡)'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确(未作答时为空)'),
    sa.Column('user_answer', sa.String(length=255), nullable=True, comment='用户实际作答内容'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['question_id'], ['bank_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uk_session_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_records')
    op.drop_table('attachments')
    op.drop_table('practice_sessions')
    op.drop_table('messages')
    op.drop_table('favorites')
    op.drop_table('bank_questions')
    op.drop_table('wrong_questions')
    op.drop_table('sessions')
    op.drop_table('question_banks')
    op.drop_table('users')
    # ### end Alembic commands ###
