"""modify_attachment_file_type

Revision ID: cc52ad35bc74
Revises: a6da4d7f3a1a
Create Date: 2026-07-07 08:49:07.132164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc52ad35bc74'
down_revision: Union[str, Sequence[str], None] = 'a6da4d7f3a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'file_type',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_comment='文件类型,如 image/jpeg',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'file_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=64),
               existing_comment='文件类型,如 image/jpeg',
               existing_nullable=True)
    # ### end Alembic commands ###
