"""change_question_session

Revision ID: dca608c143c0
Revises: a59af4d5c47b
Create Date: 2026-07-05 12:47:44.275275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dca608c143c0'
down_revision: Union[str, Sequence[str], None] = 'a59af4d5c47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_sessions', 'practice_mode',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Text(),
               existing_comment='练习模式: sequential/random/mock 等',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_sessions', 'practice_mode',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=32),
               existing_comment='练习模式: sequential/random/mock 等',
               existing_nullable=False)
    # ### end Alembic commands ###
