"""modify favorite content_ids to json array

Revision ID: f21472a159ff
Revises: 7e8d87fd07c6
Create Date: 2026-07-06 01:29:49.228600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f21472a159ff'
down_revision: Union[str, Sequence[str], None] = '7e8d87fd07c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('content_ids', sa.JSON(), nullable=False, comment='收藏的内容ID数组，对应content_type关联不同业务表'))
    op.drop_column('favorites', 'content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('content_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联的源数据ID，配合content_type对应不同表'))
    op.drop_column('favorites', 'content_ids')
    # ### end Alembic commands ###
