"""modify_practice_table

Revision ID: f90191510143
Revises: 700a65a98d34
Create Date: 2026-07-06 02:36:31.817213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f90191510143'
down_revision: Union[str, Sequence[str], None] = '700a65a98d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        UPDATE bank_questions 
        SET correct_answer = CONCAT('{"answer": "', correct_answer, '"}') 
        WHERE correct_answer NOT LIKE '{%';
    """)
    
    op.execute("""
        UPDATE practice_records 
        SET user_answer = CONCAT('{"answer": "', user_answer, '"}') 
        WHERE user_answer IS NOT NULL AND user_answer NOT LIKE '{%';
    """)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_questions', 'question_type',
               existing_type=mysql.VARCHAR(length=32),
               comment='题型: single_choice(单选)/multi_choice(多选)/essay(简答)/application(应用题) 等',
               existing_comment='题型: single_choice/multi_choice/essay 等(支持"题型练习")',
               existing_nullable=False)
    op.alter_column('bank_questions', 'difficulty_level',
               existing_type=mysql.VARCHAR(length=32),
               comment='难度: easy/medium/hard',
               existing_comment='难度: easy/medium/hard (支持"难度练习")',
               existing_nullable=True)
    op.alter_column('bank_questions', 'options_json',
               existing_type=mysql.JSON(),
               comment='选项列表(JSON格式)。规范：[{"id": "A", "content": "选项1"}, {"id": "B", "content": "选项2"}]',
               existing_comment='选项列表(JSON格式,如 ["A. 选项1", "B. 选项2"])',
               existing_nullable=True)
    op.alter_column('bank_questions', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               comment='正确答案(JSON格式)。详见下方数据格式说明',
               existing_comment='正确答案',
               existing_nullable=False)
    op.add_column('practice_records', sa.Column('option_sequence', sa.JSON(), nullable=True, comment='(选项乱序时使用)展示的选项ID顺序，如 ["C", "A", "D", "B"]，未打乱则为空或等于原始顺序'))
    op.alter_column('practice_records', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否正确(未作答时为空, 简答题可扩展支持小数得分)',
               existing_comment='是否正确(未作答时为空)',
               existing_nullable=True)
    op.alter_column('practice_records', 'user_answer',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               comment='用户实际作答内容(JSON格式)。详见下方数据格式说明',
               existing_comment='用户实际作答内容',
               existing_nullable=True)
    op.add_column('practice_sessions', sa.Column('is_options_shuffled', sa.Boolean(), nullable=True, comment='是否开启选项乱序(防作弊/提高难度)'))
    op.alter_column('practice_sessions', 'practice_mode',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=32),
               comment='练习模式: sequential(顺序)/random(乱序)/mock(模拟考) 等',
               existing_comment='练习模式: sequential/random/mock 等',
               existing_nullable=False)
    op.alter_column('practice_sessions', 'question_sequence',
               existing_type=mysql.JSON(),
               comment='生成的题目ID序列(维持顺序)。顺序练习则按题库排序，乱序则随机打乱，如 [15, 2, 8, 33]',
               existing_comment='生成的题目ID序列(维持顺序)，如 [15, 2, 8, 33]',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('practice_sessions', 'question_sequence',
               existing_type=mysql.JSON(),
               comment='生成的题目ID序列(维持顺序)，如 [15, 2, 8, 33]',
               existing_comment='生成的题目ID序列(维持顺序)。顺序练习则按题库排序，乱序则随机打乱，如 [15, 2, 8, 33]',
               existing_nullable=False)
    op.alter_column('practice_sessions', 'practice_mode',
               existing_type=sa.String(length=32),
               type_=mysql.TEXT(),
               comment='练习模式: sequential/random/mock 等',
               existing_comment='练习模式: sequential(顺序)/random(乱序)/mock(模拟考) 等',
               existing_nullable=False)
    op.drop_column('practice_sessions', 'is_options_shuffled')
    op.alter_column('practice_records', 'user_answer',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               comment='用户实际作答内容',
               existing_comment='用户实际作答内容(JSON格式)。详见下方数据格式说明',
               existing_nullable=True)
    op.alter_column('practice_records', 'is_correct',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否正确(未作答时为空)',
               existing_comment='是否正确(未作答时为空, 简答题可扩展支持小数得分)',
               existing_nullable=True)
    op.drop_column('practice_records', 'option_sequence')
    op.alter_column('bank_questions', 'correct_answer',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               comment='正确答案',
               existing_comment='正确答案(JSON格式)。详见下方数据格式说明',
               existing_nullable=False)
    op.alter_column('bank_questions', 'options_json',
               existing_type=mysql.JSON(),
               comment='选项列表(JSON格式,如 ["A. 选项1", "B. 选项2"])',
               existing_comment='选项列表(JSON格式)。规范：[{"id": "A", "content": "选项1"}, {"id": "B", "content": "选项2"}]',
               existing_nullable=True)
    op.alter_column('bank_questions', 'difficulty_level',
               existing_type=mysql.VARCHAR(length=32),
               comment='难度: easy/medium/hard (支持"难度练习")',
               existing_comment='难度: easy/medium/hard',
               existing_nullable=True)
    op.alter_column('bank_questions', 'question_type',
               existing_type=mysql.VARCHAR(length=32),
               comment='题型: single_choice/multi_choice/essay 等(支持"题型练习")',
               existing_comment='题型: single_choice(单选)/multi_choice(多选)/essay(简答)/application(应用题) 等',
               existing_nullable=False)
    # ### end Alembic commands ###
